### PR TITLE
[GraphBolt][CUDA] Dataloader `num_workers > 0` fix.

### LINKED ISSUE #6921: [GraphBolt] `RuntimeError: CUDA error: initialization error` in `sample_neighbors()` when num_workers > 0
## To Reproduce

1. build CUDA version upon DGL 2.0.x branch or install latest nightly build DGL.
2. run `DGL_HOME=/home/ubuntu/workspace/dgl_0 DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=tools:tools/distpartitioning:tests:$DGL_HOME/python:tests/python/pytorch/graphbolt:$PYTHONPATH python3 examples/sampling/graphbolt/node_classification.py --num-workers 5 --device cpu`

```
Training in cpu mode.
Loading data...
The dataset is already preprocessed.
Training...
Traceback (most recent call last):
  File "/home/ubuntu/workspace/dgl_0/examples/sampling/graphbolt/node_classification.py", line 410, in <module>
    main(args)
  File "/home/ubuntu/workspace/dgl_0/examples/sampling/graphbolt/node_classification.py", line 392, in main
    train(args, graph, features, train_set, valid_set, num_classes, model)
  File "/home/ubuntu/workspace/dgl_0/examples/sampling/graphbolt/node_classification.py", line 292, in train
    for step, data in enumerate(dataloader):
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 154, in __next__
    return self._get_next()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 142, in _get_next
    result = next(self.iterator)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 226, in wrap_next
    result = next_func(*args, **kwargs)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/datapipe.py", line 381, in __next__
    return next(self._datapipe_iter)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/base.py", line 162, in __iter__
    for data in self.datapipe:
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torchdata/datapipes/iter/util/prefetcher.py", line 103, in __iter__
    raise data
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torchdata/datapipes/iter/util/prefetcher.py", line 73, in thread_worker
    item = next(itr)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 122, in __iter__
    for data in self.datapipe:
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/dataloader.py", line 64, in __iter__
    yield from self.dataloader
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 154, in __next__
    return self._get_next()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 142, in _get_next
    result = next(self.iterator)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 226, in wrap_next
    result = next_func(*args, **kwargs)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/datapipe.py", line 381, in __next__
    return next(self._datapipe_iter)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 123, in __iter__
    yield self._apply_fn(data)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 88, in _apply_fn
    return self.fn(data)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/minibatch_transformer.py", line 38, in _transformer
    minibatch = self.transformer(minibatch)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/subgraph_sampler.py", line 57, in _sample
    ) = self.sample_subgraphs(seeds)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/impl/neighbor_sampler.py", line 138, in sample_subgraphs
    subgraph = self.sampler(
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/impl/fused_csc_sampling_graph.py", line 557, in sample_neighbors
    C_sampled_subgraph = self._sample_neighbors(
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/impl/fused_csc_sampling_graph.py", line 657, in _sample_neighbors
    return self._c_csc_graph.sample_neighbors(
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

This exception is thrown by __iter__ of NeighborSampler(datapipe=ShardingFilterIterDataPipe, deduplicate=True, fanouts=[tensor([10]), tensor([10]), tensor([10])], graph=FusedCSCSamplingGraph(csc_indptr=tensor([        0,       174,       263,  ..., 123718233, 123718242,
                                         123718280]),
                      indices=tensor([152857,  32104,  23158,  ...,  18965, 162836,  53324]),
                      num_nodes=2449029, num_edges=123718280, edge_attributes={}), prob_name=None, replace=False)
```

## Environment

 - DGL Version (e.g., 1.0): 2.0.0, nightly
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.1
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable): 12.1
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
Fixes #6921. We defer calling `is_pinned` to avoid initializing torch cuda internals by forcing the user to provide the `nodes` tensor on the GPU to be able to use pinned graph sampling via UVA. If the `nodes` or `index` tensor is not on the GPU, then we don't need to check if the graph is pinned or not. If the `nodes` tensor is on the GPU, then that means torch cuda is already initialized, and calling `is_pinned` is fine.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

File: graphbolt/src/utils.h [hunk 1]
```diff
@@ -19,6 +19,13 @@ inline bool is_accessible_from_gpu(torch::Tensor tensor) {
   return tensor.is_pinned() || tensor.device().type() == c10::DeviceType::CUDA;
 }
 
+/**
+ * @brief Checks whether the tensor is stored on the GPU.
+ */
+inline bool is_on_gpu(torch::Tensor tensor) {
```
Comment (Rhett-Ying) [inline graphbolt/src/utils.h:25]: this raises a question: how to use GPU for sampling automatically? we need to make sure `graph` is pinned or on gpu and `nodes` should be on gpu?

Comment (Rhett-Ying) [reply graphbolt/src/utils.h:25]: this is related to what will the `gb.DataLoader` interface be like, namely, how to choose sampling on GPU or CPU by user.

Comment (mfbalin) [reply graphbolt/src/utils.h:25]: If graph is pinned or is on the device and if nodes is on device, we use gpu sampling.

Comment (mfbalin) [reply graphbolt/src/utils.h:25]: It is already automatic, see the cuda examples PR.

Comment (mfbalin) [reply graphbolt/src/utils.h:25]: To dispatch to CUDA, at least one input tensor needs to be on GPU, and the rest either pinned or on GPU.

File: graphbolt/src/utils.h [hunk 2]
```diff
@@ -19,6 +19,13 @@ inline bool is_accessible_from_gpu(torch::Tensor tensor) {
...
+  return tensor.device().type() == c10::DeviceType::CUDA;
```
Comment (Rhett-Ying) [inline graphbolt/src/utils.h:26]: How about this?
```
template<typename... Args>
inline bool is_cuda(const Args&... args) {
    return (... && (args.is_cuda()));
}

```

Comment (Rhett-Ying) [reply graphbolt/src/utils.h:26]: or directly call `nodes.is_cuda()` in user code?

Comment (mfbalin) [reply graphbolt/src/utils.h:26]: I am not sure if there is a `is_cuda()` method.

Comment (mfbalin) [reply graphbolt/src/utils.h:26]: But I will try getting a variable number of argument function working.

File: graphbolt/src/utils.h (hunk 1 above)
Comment (Rhett-Ying) [reply graphbolt/src/utils.h:25]: I don't think it's automatic as user needs to call `graph.pin_memory_()` and add `copy_to()` datapipe to copy `nodes` to GPU manually in the examples you showed. This requires extra coding.

Comment (mfbalin) [reply graphbolt/src/utils.h:25]: To use the GPU, we need to insert a CopyTo at the end of the data pipes anyway. What is the difference?

Comment (mfbalin) [reply graphbolt/src/utils.h:25]: Do you think we can do better?

File: graphbolt/src/utils.h (hunk 2 above)
Comment (Rhett-Ying) [reply graphbolt/src/utils.h:26]: https://github.com/pytorch/pytorch/blob/4a10e9eed4f8faf3e68106e5e86559158d83a200/aten/src/ATen/core/TensorBase.h#L430 ?

Comment (mfbalin) [reply graphbolt/src/utils.h:26]: I wonder why they have this comment there:
https://github.com/pytorch/pytorch/blob/4a10e9eed4f8faf3e68106e5e86559158d83a200/aten/src/ATen/core/TensorBase.h#L431
```c++
// NB: this is not a native function to avoid dispatching overhead.
```

File: graphbolt/src/utils.h (hunk 1 above)
Comment (Rhett-Ying) [reply graphbolt/src/utils.h:25]: we could add such copy_to datapipe within `gb.DataLoader`(including pinning graph) and user just need to specify a target device argument for dataloader.

File: graphbolt/src/utils.h (hunk 2 above)
Comment (Rhett-Ying) [reply graphbolt/src/utils.h:26]: https://github.com/pytorch/pytorch/blob/4a10e9eed4f8faf3e68106e5e86559158d83a200/c10/core/TensorImpl.h#L1097

Comment (Rhett-Ying) [reply graphbolt/src/utils.h:26]: or use this one https://github.com/pytorch/pytorch/blob/4a10e9eed4f8faf3e68106e5e86559158d83a200/c10/core/Device.h#L81?

Comment (mfbalin) [reply graphbolt/src/utils.h:26]: The current code already uses the last one you just pointed out.

Comment (mfbalin) [reply graphbolt/src/utils.h:26]: Oh, you mean calling is_cuda on the device, Ok let me do that as the implementation is exactly the same as ours.

Comment (Rhett-Ying) [reply graphbolt/src/utils.h:26]: I think the guideline is always use available APIs(and c++ APIs are usually consistent with python in pytorch) except for performance or other issue is identified.

**Comment by Rhett-Ying** [comment]
@mfbalin could you manually run `python3 examples/sampling/graphbolt/node_classification.py --num-workers 5 --device cpu` to confirm this PR resolves the issue we hit?

**Comment by mfbalin** [comment]
> @mfbalin could you manually run `python3 examples/sampling/graphbolt/node_classification.py --num-workers 5 --device cpu` to confirm this PR resolves the issue we hit?

I already did.

File: graphbolt/src/utils.h (hunk 1 above)
Comment (mfbalin) [reply graphbolt/src/utils.h]: We can discuss this in an issue or on Slack.

**Review by Rhett-Ying — APPROVED** [review]
