### PR TITLE
[Bugfix] Allows node types with no inbound/outbound edges

### LINKED ISSUE #1320: [BUG] dgl.heterograph() not supporting node types with no inbound/outbound edges
## 🐛 Bug

See below:

## To Reproduce

```
In [2]: g = dgl.heterograph({('A', 'AB', 'B'): [(0, 1), (1, 2)]}, num_nodes_dict={'A': 3, 'B': 3, 'C': 3})

In [3]: g
Out[3]: 
Graph(num_nodes={'A': 3, 'B': 3},
      num_edges={('A', 'AB', 'B'): 2},
      metagraph=[('A', 'B')])
```

The node type `C` is missing.

## Expected behavior

Node type `C` should be there even if no edges connect to/from C.

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

A similar issue exist in the C API `CreateHeteroGraph` where we have no way to specify the number of nodes of a node type without any inbound/outbound edges.

### PR DESCRIPTION
**Pull request by BarclayII**
## Description
This fixes #1320 by adding new ctor:
```c++
CreateHeteroGraph(meta_graph, rel_graphs, num_nodes_per_type)
```
where the third argument is a `std::vector` containing the number of nodes for each node type.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

File: include/dgl/base_heterograph.h [hunk 1]
```diff
@@ -547,6 +550,25 @@ DGL_DEFINE_OBJECT_REF(FlattenedHeteroGraphRef, FlattenedHeteroGraph);
...
+
+HeteroGraphPtr CreateHeteroGraph(
+    GraphPtr meta_graph,
+    const std::vector<HeteroGraphPtr>& rel_graphs,
+    std::vector<int64_t>&& num_nodes_per_type);
+
+HeteroGraphPtr CreateHeteroGraph(
+    GraphPtr meta_graph,
+    const std::vector<HeteroGraphPtr>& rel_graphs,
+    IdArray num_nodes_per_type);
```
Comment (jermainewang) [inline include/dgl/base_heterograph.h]: The second one is weird to me. Right value reference is for mutating the argument w/ no copy which quite contradicts with the one with `const vector<>&`. In terms of using vector or IdArray, I think picking either one is fine. My practice is using IdArray if the value will participate in FFI. So my suggestion is using IdArray.

File: src/runtime/ndarray.cc [hunk 2]
```diff
@@ -263,6 +263,44 @@ GEN_FROMVECTOR_FOR(uint64_t, kDLInt, 64);
 GEN_FROMVECTOR_FOR(float, kDLFloat, 32);
 GEN_FROMVECTOR_FOR(double, kDLFloat, 64);
 
+template<typename T>
+std::vector<T> NDArray::ToVector(DLDataType dtype) const {
+  CHECK(data_->dl_tensor.ndim == 1) << "ToVector() only supported for 1D arrays";
+  CHECK(data_->dl_tensor.dtype.code == dtype.code &&
+        data_->dl_tensor.dtype.bits == dtype.bits &&
+        data_->dl_tensor.dtype.lanes == dtype.lanes) << "dtype mismatch";
```
Comment (jermainewang) [inline src/runtime/ndarray.cc]: Do we have an `==` operator overload?

File: python/dgl/convert.py [hunk 3]
```diff
@@ -441,8 +453,11 @@ def heterograph(data_dict, num_nodes_dict=None):
                     nsrc = len({n for n, d in data.nodes(data=True) if d['bipartite'] == 0})
                     ndst = data.number_of_nodes() - nsrc
             elif isinstance(data, DGLHeteroGraph):
-                # Do nothing; handled in the next loop
-                continue
+                # original node type and edge type of ``data`` is ignored.
+                assert len(data.canonical_etypes) == 1, \
+                    "Relational graphs must have only one edge type."
+                nsrc = data.number_of_nodes(data.canonical_etypes[0][0])
+                ndst = data.number_of_nodes(data.canonical_etypes[0][2])
```
Comment (jermainewang) [inline python/dgl/convert.py]: Slightly cleaner:
```python
srctype, _, dsttype = data.canonical_etypes[0]
nsrc = data.number_of_nodes(srctype)
ndst = data.number_of_nodes(dsttype)
```

File: python/dgl/graph_index.py [hunk 4]
```diff
@@ -1172,8 +1172,8 @@ def from_edge_list(elist, is_multigraph, readonly):
         src, dst = elist
     else:
         src, dst = zip(*elist)
-    src = np.asarray(src)
-    dst = np.asarray(dst)
+    src = np.array(src)
+    dst = np.array(dst)
```
Comment (jermainewang) [inline python/dgl/graph_index.py]: Why change it back?

File: include/dgl/base_heterograph.h (hunk 1 above)
Comment (jermainewang) [reply include/dgl/base_heterograph.h]: We can also extend the original interface as this right?
```c++
HeteroGraphPtr CreateHeteroGraph(
    GraphPtr meta_graph,
    const std::vector<HeteroGraphPtr>& rel_graphs,
    const IdArray num_nodes_per_type = aten::NullArray());
```

File: src/graph/heterograph.cc [hunk 5]
```diff
@@ -136,30 +141,61 @@ HeteroGraph::HeteroGraph(GraphPtr meta_graph, const std::vector<HeteroGraphPtr>&
...
-      num_verts_per_type_[dsttype] = nv;
+    if (num_verts_per_type[dsttype] < 0)
+      num_verts_per_type[dsttype] = nv;
     else
-      CHECK_EQ(num_verts_per_type_[dsttype], nv)
+      CHECK_EQ(num_verts_per_type[dsttype], nv)
         << "Mismatch number of vertices for vertex type " << dsttype;
   }
+  return num_verts_per_type;
+}
```
Comment (jermainewang) [inline src/graph/heterograph.cc]: This part seems to be a duplicate to some codes in the python side. Can we just use the C++ side?

File: src/graph/transform/union_partition.cc [hunk 6]
```diff
@@ -12,6 +12,7 @@ HeteroGraphPtr DisjointUnionHeteroGraph(
     GraphPtr meta_graph, const std::vector<HeteroGraphPtr>& component_graphs) {
   CHECK_GT(component_graphs.size(), 0) << "Input graph list is empty";
   std::vector<HeteroGraphPtr> rel_graphs(meta_graph->NumEdges());
+  std::vector<int64_t> num_nodes_per_type(meta_graph->NumVertices());
```
Comment (jermainewang) [inline src/graph/transform/union_partition.cc]: Initialize them to 0? What if the loop over the relation graph does not set some of the num_nodes?

File: src/graph/transform/compact.cc [hunk 7]
```diff
@@ -57,8 +57,11 @@ CompactGraphs(
 
   // Step 2: Relabel the nodes for each type to a smaller ID space and save the mapping.
   std::vector<IdArray> induced_nodes;
-  for (auto &hashmap : hashmaps)
+  std::vector<int64_t> num_induced_nodes;
```
Comment (jermainewang) [inline src/graph/transform/compact.cc]: Reserve the size of these two vectors.

**Comment by jermainewang** [comment]
Also, could you please double check that the newly added member is properly handled during serialization (merged in #1295) ?

File: include/dgl/base_heterograph.h (hunk 1 above)
Comment (BarclayII) [reply include/dgl/base_heterograph.h]: I don't think r-value reference is for mutating the argument (for which we should always use pointers).  The r-value reference here is for implementing moves, i.e. replacing `num_verts_per_type_` member with the given one without any copying.
Also, IdArray would be converted to `std::vector` anyway because the member `num_verts_per_type_` is a `std::vector`.

File: src/graph/transform/union_partition.cc (hunk 6 above)
Comment (BarclayII) [reply src/graph/transform/union_partition.cc]: Does `std::vector<int64_t>` initialize the contents to 0 by default?

File: src/runtime/ndarray.cc (hunk 2 above)
Comment (VoVAllen) [reply src/runtime/ndarray.cc]: https://github.com/dmlc/dgl/blob/master/src/c_api_common.h#L20

Comment (BarclayII) [reply src/runtime/ndarray.cc]: I moved both overloads to `dgl/runtime/ndarray.h`

File: python/dgl/graph_index.py (hunk 4 above)
Comment (BarclayII) [reply python/dgl/graph_index.py]: Not intended.  Reverted.

File: src/graph/heterograph.cc (hunk 5 above)
Comment (BarclayII) [reply src/graph/heterograph.cc]: Python side removed.

**Comment by BarclayII** [comment]
> Also, could you please double check that the newly added member is properly handled during serialization (merged in #1295) ?

I think so.  #1295 already serializes the number of nodes per type before I knew it.

File: src/graph/transform/union_partition.cc (hunk 6 above)
Comment (jermainewang) [reply src/graph/transform/union_partition.cc]: No. std::vector<T> initializes values by T(), but the initial value for native int is undefined in C++ standard.

File: src/graph/heterograph.cc [hunk 8]
```diff
@@ -136,30 +141,61 @@ HeteroGraph::HeteroGraph(GraphPtr meta_graph, const std::vector<HeteroGraphPtr>&
...
+  relation_graphs_ = CastToUnitGraphs(rel_graphs);
+}
+
+HeteroGraph::HeteroGraph(
+    GraphPtr meta_graph,
+    const std::vector<HeteroGraphPtr>& rel_graphs,
+    std::vector<int64_t>&& num_nodes_per_type) : BaseHeteroGraph(meta_graph) {
+  HeteroGraphSanityCheck(meta_graph, rel_graphs);
+  num_verts_per_type_ = std::move(num_nodes_per_type);
+  relation_graphs_ = CastToUnitGraphs(rel_graphs);
```
Comment (jermainewang) [inline src/graph/heterograph.cc]: Remove this too?

File: include/dgl/base_heterograph.h [hunk 9]
```diff
@@ -547,6 +553,15 @@ DGL_DEFINE_OBJECT_REF(FlattenedHeteroGraphRef, FlattenedHeteroGraph);
...
     GraphPtr meta_graph, const std::vector<HeteroGraphPtr>& rel_graphs);
 
+/*!
+ * \brief Create a heterograph from meta graph and a list of bipartite graph,
+ * additionally specifying number of nodes per type.
+ */
+HeteroGraphPtr CreateHeteroGraph(
+    GraphPtr meta_graph,
+    const std::vector<HeteroGraphPtr>& rel_graphs,
+    std::vector<int64_t> num_nodes_per_type);
```
Comment (jermainewang) [inline include/dgl/base_heterograph.h]: Let's have both of them be `std::vector` and also merge it with L553 by adding a default argument?

Comment (BarclayII) [reply include/dgl/base_heterograph.h]: If the second argument is pass-by-value then we will copy `rel_graphs` right?
