### PR TITLE
[Bug] Fix munmap() using wrong parameter

### LINKED ISSUE #2500: Memory leak when deleting shared memory ndarray at runtime
## 🐛 Bug

We are using shared memory ndarray in DGL. We found when dynamical allocating and freeing ndarray, they cannot correctly be deleted correctly on real physical memory, which lead to memory leak on shared memory at runtime.

## To Reproduce

1. run below codes 

```python3
Python 3.8.2 (default, May 20 2020, 12:05:48)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dgl
Using backend: pytorch
/home/tiger/github/dgl/python/dgl/base.py:45: DGLWarning: Detected an old version of PyTorch. Suggest using torch>=1.5.0 for the best experience.
  return warnings.warn(message, category=category, stacklevel=1)
>>> from dgl._ffi.ndarray import empty_shared_mem
>>> for i in range(10):
...     s = empty_shared_mem("test{:d}".format(i), True, (10000,100))
...     print(s)
...     del s
...
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test0 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test1 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test2 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test3 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test4 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test5 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test6 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test7 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test8 for shared memory
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[21:46:41] /home/tiger/github/dgl/src/runtime/shared_mem.cc:58: remove test9 for shared memory
>>>

```

## Expected behavior

We expect these ndarray should be deleted both on the directory /dev/shm and real psychical memory.

Shared memory objects on /dev/shm have been deleted as expected.
```shell
$ ls /dev/shm
$
```
However, these ndarray still using psychical memory.
```shell
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
shm             178G   39M  178G   1% /dev/shm
```
If we dive into the /proc/PID/maps, we can find these ndarray are only labeled by "deleted" but still in psychical memory.
These shared memory will be freed only when this process is terminated.
```shell
$ cd /proc/2774772
$ cat maps | grep test
7f0e3b81c000-7f0e3bbed000 rw-s 00000000 00:3e 1635644643                 /dev/shm/test9 (deleted)
7f0e3bbed000-7f0e3bfbe000 rw-s 00000000 00:3e 1635644642                 /dev/shm/test8 (deleted)
7f0e3bfbe000-7f0e3c38f000 rw-s 00000000 00:3e 1635644641                 /dev/shm/test7 (deleted)
7f0e3c38f000-7f0e3c760000 rw-s 00000000 00:3e 1635644640                 /dev/shm/test6 (deleted)
7f0e3c760000-7f0e3cb31000 rw-s 00000000 00:3e 1635644639                 /dev/shm/test5 (deleted)
7f0e3cb31000-7f0e3cf02000 rw-s 00000000 00:3e 1635644638                 /dev/shm/test4 (deleted)
7f0e3cf02000-7f0e3d2d3000 rw-s 00000000 00:3e 1635644637                 /dev/shm/test3 (deleted)
7f0e3d2d3000-7f0e3d6a4000 rw-s 00000000 00:3e 1635644636                 /dev/shm/test2 (deleted)
7f0e3d6a4000-7f0e3da75000 rw-s 00000000 00:3e 1635644635                 /dev/shm/test1 (deleted)
7f0e3da75000-7f0e3de46000 rw-s 00000000 00:3e 1635644634                 /dev/shm/test0 (deleted)

```

## Environment

 - DGL Version (e.g., 1.0): 0.6
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): same as the official command
 - Python version: 3.8.2
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100): 
 - Any other relevant information:

## Additional context
If using shared memory provided by [python offical](https://docs.python.org/3/library/multiprocessing.shared_memory.html), it can delete shared memory both on /dev/shm and real physical memory correctly.

### PR DESCRIPTION
**Pull request by BarclayII**
Fixes #2500 .

### CODE REVIEW

**Comment by jermainewang** [comment]
@leodestiny Would you mind testing whether the fix works on your side?

File: src/runtime/shared_mem.cc [hunk 1]
```diff
@@ -76,26 +76,28 @@ void *SharedMemory::CreateNew(size_t size) {
...
   AddResource(name, std::shared_ptr<Resource>(new SharedMemoryResource(name)));
-  auto res = ftruncate(fd, size);
+  auto res = ftruncate(fd, sz);
   CHECK_NE(res, -1)
       << "Failed to truncate the file. " << strerror(errno);
-  ptr = mmap(NULL, size, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);
+  ptr = mmap(NULL, sz, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);
   CHECK_NE(ptr, MAP_FAILED)
       << "Failed to map shared memory. mmap failed with error " << strerror(errno);
+  this->size = sz;
```
Comment (jermainewang) [inline src/runtime/shared_mem.cc:85]: This is exactly why we should follow google coding style for naming members. Would you mind changing it to `size_`?
