### PR TITLE
[hotfix] Make USE_AVX a flag in cmake to avoid compilation error for arm user

### LINKED ISSUE #2424: Compilation on osx-arm64 apple silicon m1
## 🐛 Bug

Trying to compile from source on the new macbook air with arm64e. 

## To Reproduce

mkdir build
cd build
cmake ..
make -j 8

```
/Users/yingzhu/dgl/include/intel/cpu_support.h:70:16: error: no type named 'Reg64' in namespace 'Xbyak'
  const Xbyak::Reg64 &r_out_;
        ~~~~~~~^
/Users/yingzhu/dgl/include/intel/cpu_support.h:71:16: error: no type named 'Reg64' in namespace 'Xbyak'
  const Xbyak::Reg64 &r_left_;
        ~~~~~~~^
/Users/yingzhu/dgl/include/intel/cpu_support.h:72:16: error: no type named 'Reg64' in namespace 'Xbyak'
  const Xbyak::Reg64 &r_right;
        ~~~~~~~^
/Users/yingzhu/dgl/include/intel/cpu_support.h:73:16: error: no type named 'Reg64' in namespace 'Xbyak'
  const Xbyak::Reg64 &r_size_;
        ~~~~~~~^
/Users/yingzhu/dgl/include/intel/cpu_support.h:156:42: error: use of undeclared identifier 'r9'
    alias_load<IType>(zmm0, ptr[r_out_ + r9 * sizeof(IType)]);
                                        ^
```
## Expected behavior

Build without error

## Environment

 - DGL Version from master
 - Backend Library & Version pytorch 1.7 installed
 - OS (e.g., Linux): osx-arm64
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): see above
 - Python version: 3.8.5
 - CUDA/cuDNN version (if applicable): na
 - GPU models and configuration (e.g. V100): na 
 - Any other relevant information:

## Additional context

It clearly tries to use intel-specifc code - is there support for arm? i would expect 80% of all mac users to switch to arm in the next 5 years

### PR DESCRIPTION
**Pull request by yzh119**
## Description
To fix #2424 .

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

File: src/array/cpu/spmm.h [hunk 1]
```diff
@@ -13,8 +13,10 @@
 #include <memory>
 #include "spmm_binary_ops.h"
 #if !defined(_WIN32)
+#ifdef WITH_AVX
 #include "intel/cpu_support.h"
 #endif
+#endif
```
Comment (jermainewang) [inline src/array/cpu/spmm.h:19]:
```c++
#endif  // WITH_AVX
#endif  // _WIN32
```

File: CMakeLists.txt [hunk 2]
```diff
@@ -108,6 +109,10 @@ if(USE_OPENMP)
   endif(OPENMP_FOUND)
 endif(USE_OPENMP)
 
+if(USE_AVX)
+  add_compile_definitions(WITH_AVX)
```
Comment (jermainewang) [inline CMakeLists.txt:113]: Why not call it `USE_AVX`?

**Review by jermainewang — APPROVED** [review]
Some minor comments. LGTM otherwise.
